spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
    preferIpAddress: true
    instanceId: ${spring.application.name}-3
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
  client:
    serviceUrl:
      defaultZone:  http://AdmUser:MagicaBula_2018@localhost:8761/eureka/,http://AdmUser:MagicaBula_2018@localhost:8762/eureka/

server:
  port: 8763