eureka:
  instance:
    hostname: peer3
    metadataMap:
      zone: zone3
    preferIpAddress: true
    instanceId: ${spring.application.name}-3
  server:
    #Abilita o disabilita l'auto preservazione
    enableSelfPreservation: false
    #Durata (in ms) della cache
    responseCacheUpdateIntervalMs: 30000
    #Tempo di attesa in ms di deregistrazione del servizio (def 60000)
    evictionIntervalTimerInMs: 30000
    #Tempo di attesa (in secondi) prima di accettare richieste
    waitTimeInMsWhenSyncEmpty: 5
  client:
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/,http://@localhost:8762/eureka/

server:
  port: 8763

  #Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: health,info,httptrace,refresh,bus-refresh,shutdown,hystrix.stream
  endpoint:
    shutdown:
      enabled: true
# Metodo POST con url: /actuator/refresh
# Metodo POST con url: /actuator/bus-refresh 
# Metodo POST con url: /actuator/shutdown 

spring:
  rabbitmq:
   host: ${remotesrv}
   port: 5672
   username: guest
   password: guest
  zipkin:
    baseUrl: http://${remotesrv}:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    traceId128: false
  devtools:
    restart:
      log-condition-evaluation-delta: false